import dotenv from "dotenv";
import mongoose from "mongoose";

import connectDB from "./src/config/db.js";
import Product from "./src/models/product.model.js";

dotenv.config();

await connectDB();

await Product.deleteMany();

await Product.insertMany([
  {
    name: "iPhone 16",
    category: "Mobile",
    brand: "Apple",
    price: 90000,
    stock: 20,
    rating: 4.8,
    recommendationScore: 94,
  },
  {
    name: "Galaxy S25",
    category: "Mobile",
    brand: "Samsung",
    price: 76000,
    stock: 30,
    rating: 4.6,
    recommendationScore: 90,
  },
  {
    name: "Pixel 9 Pro",
    category: "Mobile",
    brand: "Google",
    price: 82000,
    stock: 18,
    rating: 4.7,
    recommendationScore: 92,
  },
  {
    name: "OnePlus 13",
    category: "Mobile",
    brand: "OnePlus",
    price: 65000,
    stock: 35,
    rating: 4.5,
    recommendationScore: 88,
  },
  {
    name: "Nothing Phone 3",
    category: "Mobile",
    brand: "Nothing",
    price: 48000,
    stock: 40,
    rating: 4.4,
    recommendationScore: 86,
  },
  {
    name: "MacBook Air M4",
    category: "Laptop",
    brand: "Apple",
    price: 129900,
    stock: 12,
    rating: 4.9,
    recommendationScore: 98,
  },
  {
    name: "Dell XPS 14",
    category: "Laptop",
    brand: "Dell",
    price: 145000,
    stock: 10,
    rating: 4.8,
    recommendationScore: 95,
  },
  {
    name: "HP Spectre x360",
    category: "Laptop",
    brand: "HP",
    price: 135000,
    stock: 14,
    rating: 4.7,
    recommendationScore: 93,
  },
  {
    name: "Lenovo Legion Pro 5",
    category: "Laptop",
    brand: "Lenovo",
    price: 152000,
    stock: 8,
    rating: 4.8,
    recommendationScore: 96,
  },
  {
    name: "ASUS ROG Zephyrus G16",
    category: "Laptop",
    brand: "ASUS",
    price: 179000,
    stock: 6,
    rating: 4.9,
    recommendationScore: 99,
  },
  {
    name: "Sony WH-1000XM6",
    category: "Headphones",
    brand: "Sony",
    price: 32000,
    stock: 45,
    rating: 4.9,
    recommendationScore: 98,
  },
  {
    name: "AirPods Pro 3",
    category: "Headphones",
    brand: "Apple",
    price: 28000,
    stock: 50,
    rating: 4.8,
    recommendationScore: 95,
  },
  {
    name: "Bose QuietComfort Ultra",
    category: "Headphones",
    brand: "Bose",
    price: 34000,
    stock: 28,
    rating: 4.8,
    recommendationScore: 96,
  },
  {
    name: "JBL Live 770NC",
    category: "Headphones",
    brand: "JBL",
    price: 12000,
    stock: 55,
    rating: 4.4,
    recommendationScore: 84,
  },
  {
    name: "Samsung Galaxy Watch Ultra",
    category: "Smartwatch",
    brand: "Samsung",
    price: 48000,
    stock: 25,
    rating: 4.7,
    recommendationScore: 92,
  },
  {
    name: "Apple Watch Series 10",
    category: "Smartwatch",
    brand: "Apple",
    price: 52000,
    stock: 22,
    rating: 4.9,
    recommendationScore: 98,
  },
  {
    name: "Garmin Forerunner 965",
    category: "Smartwatch",
    brand: "Garmin",
    price: 56000,
    stock: 15,
    rating: 4.8,
    recommendationScore: 95,
  },
  {
    name: "iPad Air M3",
    category: "Tablet",
    brand: "Apple",
    price: 69900,
    stock: 18,
    rating: 4.8,
    recommendationScore: 96,
  },
  {
    name: "Galaxy Tab S10",
    category: "Tablet",
    brand: "Samsung",
    price: 64000,
    stock: 20,
    rating: 4.6,
    recommendationScore: 90,
  },
  {
    name: "Xiaomi Pad 7",
    category: "Tablet",
    brand: "Xiaomi",
    price: 34000,
    stock: 32,
    rating: 4.5,
    recommendationScore: 87,
  },
  {
    name: "Canon EOS R10",
    category: "Camera",
    brand: "Canon",
    price: 89999,
    stock: 10,
    rating: 4.8,
    recommendationScore: 94,
  },
  {
    name: "Sony Alpha A6700",
    category: "Camera",
    brand: "Sony",
    price: 119999,
    stock: 8,
    rating: 4.9,
    recommendationScore: 98,
  },
  {
    name: "Nikon Z50 II",
    category: "Camera",
    brand: "Nikon",
    price: 95999,
    stock: 9,
    rating: 4.7,
    recommendationScore: 92,
  },
  {
    name: "Logitech MX Master 3S",
    category: "Accessories",
    brand: "Logitech",
    price: 8999,
    stock: 60,
    rating: 4.9,
    recommendationScore: 97,
  },
  {
    name: "Keychron K8 Pro",
    category: "Accessories",
    brand: "Keychron",
    price: 9999,
    stock: 45,
    rating: 4.8,
    recommendationScore: 95,
  },
  {
    name: "Samsung T9 SSD 2TB",
    category: "Storage",
    brand: "Samsung",
    price: 18999,
    stock: 30,
    rating: 4.8,
    recommendationScore: 94,
  },
  {
    name: "SanDisk Extreme Pro 1TB",
    category: "Storage",
    brand: "SanDisk",
    price: 12499,
    stock: 35,
    rating: 4.7,
    recommendationScore: 91,
  },
  {
    name: "LG UltraGear 27 OLED",
    category: "Monitor",
    brand: "LG",
    price: 79999,
    stock: 12,
    rating: 4.9,
    recommendationScore: 98,
  },
  {
    name: "Dell UltraSharp U2725QE",
    category: "Monitor",
    brand: "Dell",
    price: 58999,
    stock: 14,
    rating: 4.8,
    recommendationScore: 95,
  },
  {
    name: "BenQ MOBIUZ EX2710Q",
    category: "Monitor",
    brand: "BenQ",
    price: 31999,
    stock: 20,
    rating: 4.6,
    recommendationScore: 89,
  }
]);

console.log("Database Seeded");

process.exit();